#!/usr/bin/env sh

set -eu

[ "${#}" -gt 0 ] || {
    echo "usage: ${0} [directory]..." >&2
    exit 2
}

for pkg; do
    echo "${0}: stowing $pkg"
    stow --no-folding --restow --target="${HOME}" "${pkg}"
done
